# Generated by Django 4.1.1 on 2022-09-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, upload_to='resource_images'),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
